language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: m8SE6q+oUoftHOedVfkZWe2KsJoPrNaqfLUv0+NCiNg+sZOlRHj1D7yRpE5cjopZmR/2ZnINIHxnPk330uSDkkVTd0w/9LEiFtkRaoknoQT7P/mxEeyu1hjmp5R/SqlMlPF12F9MdY+dNrgQLJb1jxns3VgbbIIggn9AtGvlAo5rxa0bUfsc+7xLH3apxFVUdty6QZtZAKDNC1kG01o/n3D5mqgfCU2eLEznQasQSo6gA79YRR1nRAEPp0qqjNx96dNmLXjD1EGmp7tVu3KPA3aI9aXRWuUgfwZmCgwF8rbj0ia+NTPqcy/jPqNTSSVk+H8BPsAKHVAy01D+r2SGEua1EhIr5xSsW9pcmHXjuG6aSZvo4ALXA8ANkjuHOciOPrPmhKyz9aMhyXS01hfCBPNOeFOKVB3b7vxb3p9P9z6Yo8KrJPcKUvXggRFnLlyWLJB0dRVtXQQwbIkMcQEPPrMce7EwU+G+xeXbdklhqZ6eIPhiZ5sYVYbTvI+pxc5PK+zZyna2yjPNliMoTRUBOaOZpIELgfmYjljCgk+JTi+aScY0jHnWoayUVoRE+v5ugk+fiCuhfb7qWPFdJYxsmYmPr2BqZo5oADduUcWRJXp5jHksfkgNy4VH8tOk5bH8WYf7D5QX9U8wJPm8gvXoWSgDrru9cXLONqkM7X8BoE0=
